insert into "servicos".municipio values (  1	,	'Aceguá'	,	6	, true);	
insert into "servicos".municipio values (	2	,	'Água Santa'	,	9	, true);	
insert into "servicos".municipio values (	3	,	'Agudo'	,	8	, true);	
insert into "servicos".municipio values (	4	,	'Ajuricaba'	,	7	, true);	
insert into "servicos".municipio values (	5	,	'Alecrim'	,	7	, true);	
insert into "servicos".municipio values (	6	,	'Alegrete'	,	6	, true);	
insert into "servicos".municipio values (	7	,	'Alegria'	,	7	, true);	
insert into "servicos".municipio values (	8	,	'Almirante Tamandaré do Sul'	,	9	, true);	
insert into "servicos".municipio values (	9	,	'Alpestre'	,	9	, true);	
insert into "servicos".municipio values (	10	,	'Alto Alegre'	,	9	, true);	
insert into "servicos".municipio values (	11	,	'Alto Feliz'	,	1	, true);	
insert into "servicos".municipio values (	12	,	'Alvorada'	,	1	, true);	
insert into "servicos".municipio values (	13	,	'Amaral Ferrador'	,	5	, true);	
insert into "servicos".municipio values (	14	,	'Ametista do Sul'	,	9	, true);	
insert into "servicos".municipio values (	15	,	'André da Rocha'	,	3	, true);	
insert into "servicos".municipio values (	16	,	'Anta Gorda'	,	2	, true);	
insert into "servicos".municipio values (	17	,	'Antônio Prado'	,	3	, true);	
insert into "servicos".municipio values (	18	,	'Arambaré'	,	1	, true);	
insert into "servicos".municipio values (	19	,	'Araricá'	,	1	, true);	
insert into "servicos".municipio values (	20	,	'Aratiba'	,	9	, true);	
insert into "servicos".municipio values (	21	,	'Arroio do Meio'	,	2	, true);	
insert into "servicos".municipio values (	22	,	'Arroio do Padre'	,	5	, true);	
insert into "servicos".municipio values (	23	,	'Arroio do Sal'	,	4	, true);	
insert into "servicos".municipio values (	24	,	'Arroio do Tigre'	,	2	, true);	
insert into "servicos".municipio values (	25	,	'Arroio dos Ratos'	,	1	, true);	
insert into "servicos".municipio values (	26	,	'Arroio Grande'	,	5	, true);	
insert into "servicos".municipio values (	27	,	'Arvorezinha'	,	2	, true);	
insert into "servicos".municipio values (	28	,	'Augusto Pestana'	,	7	, true);	
insert into "servicos".municipio values (	29	,	'Áurea'	,	9	, true);	
insert into "servicos".municipio values (	30	,	'Bagé'	,	6	, true);	
insert into "servicos".municipio values (	31	,	'Balneário Pinhal'	,	4	, true);	
insert into "servicos".municipio values (	32	,	'Barão'	,	1	, true);	
insert into "servicos".municipio values (	33	,	'Barão de Cotegipe'	,	9	, true);	
insert into "servicos".municipio values (	34	,	'Barão do Triunfo'	,	1	, true);	
insert into "servicos".municipio values (	35	,	'Barra do Guarita'	,	7	, true);	
insert into "servicos".municipio values (	36	,	'Barra do Quaraí'	,	6	, true);	
insert into "servicos".municipio values (	37	,	'Barra do Ribeiro'	,	1	, true);	
insert into "servicos".municipio values (	38	,	'Barra do Rio Azul'	,	9	, true);	
insert into "servicos".municipio values (	39	,	'Barra Funda'	,	9	, true);	
insert into "servicos".municipio values (	40	,	'Barracão'	,	9	, true);	
insert into "servicos".municipio values (	41	,	'Barros Cassal'	,	9	, true);	
insert into "servicos".municipio values (	42	,	'Benjamin Constant do Sul'	,	9	, true);	
insert into "servicos".municipio values (	43	,	'Bento Gonçalves'	,	3	, true);	
insert into "servicos".municipio values (	44	,	'Boa Vista das Missões'	,	9	, true);	
insert into "servicos".municipio values (	45	,	'Boa Vista do Buricá'	,	7	, true);	
insert into "servicos".municipio values (	46	,	'Boa Vista do Cadeado'	,	8	, true);	
insert into "servicos".municipio values (	47	,	'Boa Vista do Incra'	,	8	, true);	
insert into "servicos".municipio values (	48	,	'Boa Vista do Sul'	,	3	, true);	
insert into "servicos".municipio values (	49	,	'Bom Jesus'	,	3	, true);	
insert into "servicos".municipio values (	50	,	'Bom Princípio'	,	1	, true);	
insert into "servicos".municipio values (	51	,	'Bom Progresso'	,	7	, true);	
insert into "servicos".municipio values (	52	,	'Bom Retiro do Sul'	,	2	, true);	
insert into "servicos".municipio values (	53	,	'Boqueirão do Leão'	,	2	, true);	
insert into "servicos".municipio values (	54	,	'Bossoroca'	,	7	, true);	
insert into "servicos".municipio values (	55	,	'Bozano'	,	7	, true);	
insert into "servicos".municipio values (	56	,	'Braga'	,	7	, true);	
insert into "servicos".municipio values (	57	,	'Brochier'	,	1	, true);	
insert into "servicos".municipio values (	58	,	'Butiá'	,	1	, true);	
insert into "servicos".municipio values (	59	,	'Caçapava do Sul'	,	6	, true);	
insert into "servicos".municipio values (	60	,	'Cacequi'	,	8	, true);	
insert into "servicos".municipio values (	61	,	'Cachoeira do Sul'	,	8	, true);	
insert into "servicos".municipio values (	62	,	'Cachoeirinha'	,	1	, true);	
insert into "servicos".municipio values (	63	,	'Cacique Doble'	,	9	, true);	
insert into "servicos".municipio values (	64	,	'Caibaté'	,	7	, true);	
insert into "servicos".municipio values (	65	,	'Caiçara'	,	9	, true);	
insert into "servicos".municipio values (	66	,	'Camaquã'	,	1	, true);	
insert into "servicos".municipio values (	67	,	'Camargo'	,	9	, true);	
insert into "servicos".municipio values (	68	,	'Cambará do Sul'	,	3	, true);	
insert into "servicos".municipio values (	69	,	'Campestre da Serra'	,	3	, true);	
insert into "servicos".municipio values (	70	,	'Campina das Missões'	,	7	, true);	
insert into "servicos".municipio values (	71	,	'Campinas do Sul'	,	9	, true);	
insert into "servicos".municipio values (	72	,	'Campo Bom'	,	1	, true);	
insert into "servicos".municipio values (	73	,	'Campo Novo'	,	7	, true);	
insert into "servicos".municipio values (	74	,	'Campos Borges'	,	9	, true);	
insert into "servicos".municipio values (	75	,	'Candelária'	,	2	, true);	
insert into "servicos".municipio values (	76	,	'Cândido Godói'	,	7	, true);	
insert into "servicos".municipio values (	77	,	'Candiota'	,	6	, true);	
insert into "servicos".municipio values (	78	,	'Canela'	,	3	, true);	
insert into "servicos".municipio values (	79	,	'Canguçu'	,	5	, true);	
insert into "servicos".municipio values (	80	,	'Canoas'	,	1	, true);	
insert into "servicos".municipio values (	81	,	'Canudos do Vale'	,	2	, true);	
insert into "servicos".municipio values (	82	,	'Capão Bonito do Sul'	,	9	, true);	
insert into "servicos".municipio values (	83	,	'Capão da Canoa'	,	4	, true);	
insert into "servicos".municipio values (	84	,	'Capão do Cipó'	,	8	, true);	
insert into "servicos".municipio values (	85	,	'Capão do Leão'	,	5	, true);	
insert into "servicos".municipio values (	86	,	'Capela de Santana'	,	1	, true);	
insert into "servicos".municipio values (	87	,	'Capitão'	,	2	, true);	
insert into "servicos".municipio values (	88	,	'Capivari do Sul'	,	4	, true);	
insert into "servicos".municipio values (	89	,	'Caraá'	,	4	, true);	
insert into "servicos".municipio values (	90	,	'Carazinho'	,	9	, true);	
insert into "servicos".municipio values (	91	,	'Carlos Barbosa'	,	3	, true);	
insert into "servicos".municipio values (	92	,	'Carlos Gomes'	,	9	, true);	
insert into "servicos".municipio values (	93	,	'Casca'	,	9	, true);	
insert into "servicos".municipio values (	94	,	'Caseiros'	,	9	, true);	
insert into "servicos".municipio values (	95	,	'Catuípe'	,	7	, true);	
insert into "servicos".municipio values (	96	,	'Caxias do Sul'	,	3	, true);	
insert into "servicos".municipio values (	97	,	'Centenário'	,	9	, true);	
insert into "servicos".municipio values (	98	,	'Cerrito'	,	5	, true);	
insert into "servicos".municipio values (	99	,	'Cerro Branco'	,	8	, true);	
insert into "servicos".municipio values (	100	,	'Cerro Grande'	,	9	, true);	
insert into "servicos".municipio values (	101	,	'Cerro Grande do Sul'	,	1	, true);	
insert into "servicos".municipio values (	102	,	'Cerro Largo'	,	7	, true);	
insert into "servicos".municipio values (	103	,	'Chapada'	,	9	, true);	
insert into "servicos".municipio values (	104	,	'Charqueadas'	,	1	, true);	
insert into "servicos".municipio values (	105	,	'Charrua'	,	9	, true);	
insert into "servicos".municipio values (	106	,	'Chiapetta'	,	7	, true);	
insert into "servicos".municipio values (	107	,	'Chuí'	,	5	, true);	
insert into "servicos".municipio values (	108	,	'Chuvisca'	,	1	, true);	
insert into "servicos".municipio values (	109	,	'Cidreira'	,	4	, true);	
insert into "servicos".municipio values (	110	,	'Ciríaco'	,	9	, true);	
insert into "servicos".municipio values (	111	,	'Colinas'	,	2	, true);	
insert into "servicos".municipio values (	112	,	'Colorado'	,	8	, true);	
insert into "servicos".municipio values (	113	,	'Condor'	,	7	, true);	
insert into "servicos".municipio values (	114	,	'Constantina'	,	9	, true);	
insert into "servicos".municipio values (	115	,	'Coqueiro Baixo'	,	2	, true);	
insert into "servicos".municipio values (	116	,	'Coqueiros do Sul'	,	9	, true);	
insert into "servicos".municipio values (	117	,	'Coronel Barros'	,	7	, true);	
insert into "servicos".municipio values (	118	,	'Coronel Bicaco'	,	7	, true);	
insert into "servicos".municipio values (	119	,	'Coronel Pilar'	,	3	, true);	
insert into "servicos".municipio values (	120	,	'Cotiporã'	,	3	, true);	
insert into "servicos".municipio values (	121	,	'Coxilha'	,	9	, true);	
insert into "servicos".municipio values (	122	,	'Crissiumal'	,	7	, true);	
insert into "servicos".municipio values (	123	,	'Cristal'	,	1	, true);	
insert into "servicos".municipio values (	124	,	'Cristal do Sul'	,	9	, true);	
insert into "servicos".municipio values (	125	,	'Cruz Alta'	,	8	, true);	
insert into "servicos".municipio values (	126	,	'Cruzaltense'	,	9	, true);	
insert into "servicos".municipio values (	127	,	'Cruzeiro do Sul'	,	2	, true);	
insert into "servicos".municipio values (	128	,	'David Canabarro'	,	9	, true);	
insert into "servicos".municipio values (	129	,	'Derrubadas'	,	7	, true);	
insert into "servicos".municipio values (	130	,	'Dezesseis de Novembro'	,	7	, true);	
insert into "servicos".municipio values (	131	,	'Dilermando de Aguiar'	,	8	, true);	
insert into "servicos".municipio values (	132	,	'Dois Irmãos'	,	1	, true);	
insert into "servicos".municipio values (	133	,	'Dois Irmãos das Missões'	,	9	, true);	
insert into "servicos".municipio values (	134	,	'Dois Lajeados'	,	2	, true);	
insert into "servicos".municipio values (	135	,	'Dom Feliciano'	,	1	, true);	
insert into "servicos".municipio values (	136	,	'Dom Pedrito'	,	6	, true);	
insert into "servicos".municipio values (	137	,	'Dom Pedro de Alcântara'	,	4	, true);	
insert into "servicos".municipio values (	138	,	'Dona Francisca'	,	8	, true);	
insert into "servicos".municipio values (	139	,	'Doutor Maurício Cardoso'	,	7	, true);	
insert into "servicos".municipio values (	140	,	'Doutor Ricardo'	,	2	, true);	
insert into "servicos".municipio values (	141	,	'Eldorado do Sul'	,	1	, true);	
insert into "servicos".municipio values (	142	,	'Encantado'	,	2	, true);	
insert into "servicos".municipio values (	143	,	'Encruzilhada do Sul'	,	2	, true);	
insert into "servicos".municipio values (	144	,	'Engenho Velho'	,	9	, true);	
insert into "servicos".municipio values (	145	,	'Entre Rios do Sul'	,	9	, true);	
insert into "servicos".municipio values (	146	,	'Entre-Ijuís'	,	7	, true);	
insert into "servicos".municipio values (	147	,	'Erebango'	,	9	, true);	
insert into "servicos".municipio values (	148	,	'Erechim'	,	9	, true);	
insert into "servicos".municipio values (	149	,	'Ernestina'	,	9	, true);	
insert into "servicos".municipio values (	150	,	'Erval Grande'	,	9	, true);	
insert into "servicos".municipio values (	151	,	'Erval Seco'	,	9	, true);	
insert into "servicos".municipio values (	152	,	'Esmeralda'	,	3	, true);	
insert into "servicos".municipio values (	153	,	'Esperança do Sul'	,	7	, true);	
insert into "servicos".municipio values (	154	,	'Espumoso'	,	9	, true);	
insert into "servicos".municipio values (	155	,	'Estação'	,	9	, true);	
insert into "servicos".municipio values (	156	,	'Estância Velha'	,	1	, true);	
insert into "servicos".municipio values (	157	,	'Esteio'	,	1	, true);	
insert into "servicos".municipio values (	158	,	'Estrela'	,	2	, true);	
insert into "servicos".municipio values (	159	,	'Estrela Velha'	,	2	, true);	
insert into "servicos".municipio values (	160	,	'Eugênio de Castro'	,	7	, true);	
insert into "servicos".municipio values (	161	,	'Fagundes Varela'	,	3	, true);	
insert into "servicos".municipio values (	162	,	'Farroupilha'	,	3	, true);	
insert into "servicos".municipio values (	163	,	'Faxinal do Soturno'	,	8	, true);	
insert into "servicos".municipio values (	164	,	'Faxinalzinho'	,	9	, true);	
insert into "servicos".municipio values (	165	,	'Fazenda Vila Nova'	,	2	, true);	
insert into "servicos".municipio values (	166	,	'Feliz'	,	1	, true);	
insert into "servicos".municipio values (	167	,	'Flores da Cunha'	,	3	, true);	
insert into "servicos".municipio values (	168	,	'Floriano Peixoto'	,	9	, true);	
insert into "servicos".municipio values (	169	,	'Fontoura Xavier'	,	9	, true);	
insert into "servicos".municipio values (	170	,	'Formigueiro'	,	8	, true);	
insert into "servicos".municipio values (	171	,	'Forquetinha'	,	2	, true);	
insert into "servicos".municipio values (	172	,	'Fortaleza dos Valos'	,	8	, true);	
insert into "servicos".municipio values (	173	,	'Frederico Westphalen'	,	9	, true);	
insert into "servicos".municipio values (	174	,	'Garibaldi'	,	3	, true);	
insert into "servicos".municipio values (	175	,	'Garruchos'	,	7	, true);	
insert into "servicos".municipio values (	176	,	'Gaurama'	,	9	, true);	
insert into "servicos".municipio values (	177	,	'General Câmara'	,	2	, true);	
insert into "servicos".municipio values (	178	,	'Gentil'	,	9	, true);	
insert into "servicos".municipio values (	179	,	'Getúlio Vargas'	,	9	, true);	
insert into "servicos".municipio values (	180	,	'Giruá'	,	7	, true);	
insert into "servicos".municipio values (	181	,	'Glorinha'	,	1	, true);	
insert into "servicos".municipio values (	182	,	'Gramado'	,	3	, true);	
insert into "servicos".municipio values (	183	,	'Gramado dos Loureiros'	,	9	, true);	
insert into "servicos".municipio values (	184	,	'Gramado Xavier'	,	9	, true);	
insert into "servicos".municipio values (	185	,	'Gravataí'	,	1	, true);	
insert into "servicos".municipio values (	186	,	'Guabiju'	,	3	, true);	
insert into "servicos".municipio values (	187	,	'Guaíba'	,	1	, true);	
insert into "servicos".municipio values (	188	,	'Guaporé'	,	3	, true);	
insert into "servicos".municipio values (	189	,	'Guarani das Missões'	,	7	, true);	
insert into "servicos".municipio values (	190	,	'Harmonia'	,	1	, true);	
insert into "servicos".municipio values (	191	,	'Herval'	,	5	, true);	
insert into "servicos".municipio values (	192	,	'Herveiras'	,	2	, true);	
insert into "servicos".municipio values (	193	,	'Horizontina'	,	7	, true);	
insert into "servicos".municipio values (	194	,	'Hulha Negra'	,	6	, true);	
insert into "servicos".municipio values (	195	,	'Humaitá'	,	7	, true);	
insert into "servicos".municipio values (	196	,	'Ibarama'	,	2	, true);	
insert into "servicos".municipio values (	197	,	'Ibiaçá'	,	9	, true);	
insert into "servicos".municipio values (	198	,	'Ibiraiaras'	,	9	, true);	
insert into "servicos".municipio values (	199	,	'Ibirapuitã'	,	9	, true);	
insert into "servicos".municipio values (	200	,	'Ibirubá'	,	8	, true);	
insert into "servicos".municipio values (	201	,	'Igrejinha'	,	1	, true);	
insert into "servicos".municipio values (	202	,	'Ijuí'	,	7	, true);	
insert into "servicos".municipio values (	203	,	'Ilópolis'	,	2	, true);	
insert into "servicos".municipio values (	204	,	'Imbé'	,	4	, true);	
insert into "servicos".municipio values (	205	,	'Imigrante'	,	2	, true);	
insert into "servicos".municipio values (	206	,	'Independência'	,	7	, true);	
insert into "servicos".municipio values (	207	,	'Inhacorá'	,	7	, true);	
insert into "servicos".municipio values (	208	,	'Ipê'	,	3	, true);	
insert into "servicos".municipio values (	209	,	'Ipiranga do Sul'	,	9	, true);	
insert into "servicos".municipio values (	210	,	'Iraí'	,	9	, true);	
insert into "servicos".municipio values (	211	,	'Itaara'	,	8	, true);	
insert into "servicos".municipio values (	212	,	'Itacurubi'	,	6	, true);	
insert into "servicos".municipio values (	213	,	'Itapuca'	,	9	, true);	
insert into "servicos".municipio values (	214	,	'Itaqui'	,	6	, true);	
insert into "servicos".municipio values (	215	,	'Itati'	,	4	, true);	
insert into "servicos".municipio values (	216	,	'Itatiba do Sul'	,	9	, true);	
insert into "servicos".municipio values (	217	,	'Ivorá'	,	8	, true);	
insert into "servicos".municipio values (	218	,	'Ivoti'	,	1	, true);	
insert into "servicos".municipio values (	219	,	'Jaboticaba'	,	9	, true);	
insert into "servicos".municipio values (	220	,	'Jacuizinho'	,	9	, true);	
insert into "servicos".municipio values (	221	,	'Jacutinga'	,	9	, true);	
insert into "servicos".municipio values (	222	,	'Jaguarão'	,	5	, true);	
insert into "servicos".municipio values (	223	,	'Jaguari'	,	8	, true);	
insert into "servicos".municipio values (	224	,	'Jaquirana'	,	3	, true);	
insert into "servicos".municipio values (	225	,	'Jari'	,	8	, true);	
insert into "servicos".municipio values (	226	,	'Jóia'	,	7	, true);	
insert into "servicos".municipio values (	227	,	'Júlio de Castilhos'	,	8	, true);	
insert into "servicos".municipio values (	228	,	'Lagoa Bonita do Sul'	,	2	, true);	
insert into "servicos".municipio values (	229	,	'Lagoa dos Três Cantos'	,	8	, true);	
insert into "servicos".municipio values (	230	,	'Lagoa Vermelha'	,	9	, true);	
insert into "servicos".municipio values (	231	,	'Lagoão'	,	9	, true);	
insert into "servicos".municipio values (	232	,	'Lajeado'	,	2	, true);	
insert into "servicos".municipio values (	233	,	'Lajeado do Bugre'	,	9	, true);	
insert into "servicos".municipio values (	234	,	'Lavras do Sul'	,	6	, true);	
insert into "servicos".municipio values (	235	,	'Liberato Salzano'	,	9	, true);	
insert into "servicos".municipio values (	236	,	'Lindolfo Collor'	,	1	, true);	
insert into "servicos".municipio values (	237	,	'Linha Nova'	,	1	, true);	
insert into "servicos".municipio values (	238	,	'Maçambará'	,	6	, true);	
insert into "servicos".municipio values (	239	,	'Machadinho'	,	9	, true);	
insert into "servicos".municipio values (	240	,	'Mampituba'	,	4	, true);	
insert into "servicos".municipio values (	241	,	'Manoel Viana'	,	6	, true);	
insert into "servicos".municipio values (	242	,	'Maquiné'	,	4	, true);	
insert into "servicos".municipio values (	243	,	'Maratá'	,	1	, true);	
insert into "servicos".municipio values (	244	,	'Marau'	,	9	, true);	
insert into "servicos".municipio values (	245	,	'Marcelino Ramos'	,	9	, true);	
insert into "servicos".municipio values (	246	,	'Mariana Pimentel'	,	1	, true);	
insert into "servicos".municipio values (	247	,	'Mariano Moro'	,	9	, true);	
insert into "servicos".municipio values (	248	,	'Marques de Souza'	,	2	, true);	
insert into "servicos".municipio values (	249	,	'Mata'	,	8	, true);	
insert into "servicos".municipio values (	250	,	'Mato Castelhano'	,	9	, true);	
insert into "servicos".municipio values (	251	,	'Mato Leitão'	,	2	, true);	
insert into "servicos".municipio values (	252	,	'Mato Queimado'	,	7	, true);	
insert into "servicos".municipio values (	253	,	'Maximiliano de Almeida'	,	9	, true);	
insert into "servicos".municipio values (	254	,	'Minas do Leão'	,	1	, true);	
insert into "servicos".municipio values (	255	,	'Miraguaí'	,	7	, true);	
insert into "servicos".municipio values (	256	,	'Montauri'	,	3	, true);	
insert into "servicos".municipio values (	257	,	'Monte Alegre dos Campos'	,	3	, true);	
insert into "servicos".municipio values (	258	,	'Monte Belo do Sul'	,	3	, true);	
insert into "servicos".municipio values (	259	,	'Montenegro'	,	1	, true);	
insert into "servicos".municipio values (	260	,	'Mormaço'	,	9	, true);	
insert into "servicos".municipio values (	261	,	'Morrinhos do Sul'	,	4	, true);	
insert into "servicos".municipio values (	262	,	'Morro Redondo'	,	5	, true);	
insert into "servicos".municipio values (	263	,	'Morro Reuter'	,	1	, true);	
insert into "servicos".municipio values (	264	,	'Mostardas'	,	4	, true);	
insert into "servicos".municipio values (	265	,	'Muçum'	,	2	, true);	
insert into "servicos".municipio values (	266	,	'Muitos Capões'	,	3	, true);	
insert into "servicos".municipio values (	267	,	'Muliterno'	,	9	, true);	
insert into "servicos".municipio values (	268	,	'Não-Me-Toque'	,	8	, true);	
insert into "servicos".municipio values (	269	,	'Nicolau Vergueiro'	,	9	, true);	
insert into "servicos".municipio values (	270	,	'Nonoai'	,	9	, true);	
insert into "servicos".municipio values (	271	,	'Nova Alvorada'	,	9	, true);	
insert into "servicos".municipio values (	272	,	'Nova Araçá'	,	3	, true);	
insert into "servicos".municipio values (	273	,	'Nova Bassano'	,	3	, true);	
insert into "servicos".municipio values (	274	,	'Nova Boa Vista'	,	9	, true);	
insert into "servicos".municipio values (	275	,	'Nova Bréscia'	,	2	, true);	
insert into "servicos".municipio values (	276	,	'Nova Candelária'	,	7	, true);	
insert into "servicos".municipio values (	277	,	'Nova Esperança do Sul'	,	8	, true);	
insert into "servicos".municipio values (	278	,	'Nova Hartz'	,	1	, true);	
insert into "servicos".municipio values (	279	,	'Nova Pádua'	,	3	, true);	
insert into "servicos".municipio values (	280	,	'Nova Palma'	,	8	, true);	
insert into "servicos".municipio values (	281	,	'Nova Petrópolis'	,	3	, true);	
insert into "servicos".municipio values (	282	,	'Nova Prata'	,	3	, true);	
insert into "servicos".municipio values (	283	,	'Nova Ramada'	,	7	, true);	
insert into "servicos".municipio values (	284	,	'Nova Roma do Sul'	,	3	, true);	
insert into "servicos".municipio values (	285	,	'Nova Santa Rita'	,	1	, true);	
insert into "servicos".municipio values (	286	,	'Novo Barreiro'	,	9	, true);	
insert into "servicos".municipio values (	287	,	'Novo Cabrais'	,	8	, true);	
insert into "servicos".municipio values (	288	,	'Novo Hamburgo'	,	1	, true);	
insert into "servicos".municipio values (	289	,	'Novo Machado'	,	7	, true);	
insert into "servicos".municipio values (	290	,	'Novo Tiradentes'	,	9	, true);	
insert into "servicos".municipio values (	291	,	'Novo Xingú'	,	9	, true);	
insert into "servicos".municipio values (	292	,	'Osório'	,	4	, true);	
insert into "servicos".municipio values (	293	,	'Paim Filho'	,	9	, true);	
insert into "servicos".municipio values (	294	,	'Palmares do Sul'	,	4	, true);	
insert into "servicos".municipio values (	295	,	'Palmeira das Missões'	,	9	, true);	
insert into "servicos".municipio values (	296	,	'Palmitinho'	,	9	, true);	
insert into "servicos".municipio values (	297	,	'Panambi'	,	7	, true);	
insert into "servicos".municipio values (	298	,	'Pantano Grande'	,	2	, true);	
insert into "servicos".municipio values (	299	,	'Paraí'	,	3	, true);	
insert into "servicos".municipio values (	300	,	'Paraíso do Sul'	,	8	, true);	
insert into "servicos".municipio values (	301	,	'Pareci Novo'	,	1	, true);	
insert into "servicos".municipio values (	302	,	'Parobé'	,	1	, true);	
insert into "servicos".municipio values (	303	,	'Passa Sete'	,	2	, true);	
insert into "servicos".municipio values (	304	,	'Passo do Sobrado'	,	2	, true);	
insert into "servicos".municipio values (	305	,	'Passo Fundo'	,	9	, true);	
insert into "servicos".municipio values (	306	,	'Paulo Bento'	,	9	, true);	
insert into "servicos".municipio values (	307	,	'Paverama'	,	2	, true);	
insert into "servicos".municipio values (	308	,	'Pedras Altas'	,	5	, true);	
insert into "servicos".municipio values (	309	,	'Pedro Osório'	,	5	, true);	
insert into "servicos".municipio values (	310	,	'Pejuçara'	,	7	, true);	
insert into "servicos".municipio values (	311	,	'Pelotas'	,	5	, true);	
insert into "servicos".municipio values (	312	,	'Picada Café'	,	3	, true);	
insert into "servicos".municipio values (	313	,	'Pinhal'	,	9	, true);	
insert into "servicos".municipio values (	314	,	'Pinhal da Serra'	,	3	, true);	
insert into "servicos".municipio values (	315	,	'Pinhal Grande'	,	8	, true);	
insert into "servicos".municipio values (	316	,	'Pinheirinho do Vale'	,	9	, true);	
insert into "servicos".municipio values (	317	,	'Pinheiro Machado'	,	5	, true);	
insert into "servicos".municipio values (	318	,	'Pirapó'	,	7	, true);	
insert into "servicos".municipio values (	319	,	'Piratini'	,	5	, true);	
insert into "servicos".municipio values (	320	,	'Planalto'	,	9	, true);	
insert into "servicos".municipio values (	321	,	'Poço das Antas'	,	2	, true);	
insert into "servicos".municipio values (	322	,	'Pontão'	,	9	, true);	
insert into "servicos".municipio values (	323	,	'Ponte Preta'	,	9	, true);	
insert into "servicos".municipio values (	324	,	'Portão'	,	1	, true);	
insert into "servicos".municipio values (	325	,	'Porto Alegre'	,	1	, true);	
insert into "servicos".municipio values (	326	,	'Porto Lucena'	,	7	, true);	
insert into "servicos".municipio values (	327	,	'Porto Mauá'	,	7	, true);	
insert into "servicos".municipio values (	328	,	'Porto Vera Cruz'	,	7	, true);	
insert into "servicos".municipio values (	329	,	'Porto Xavier'	,	7	, true);	
insert into "servicos".municipio values (	330	,	'Pouso Novo'	,	2	, true);	
insert into "servicos".municipio values (	331	,	'Presidente Lucena'	,	1	, true);	
insert into "servicos".municipio values (	332	,	'Progresso'	,	2	, true);	
insert into "servicos".municipio values (	333	,	'Protásio Alves'	,	3	, true);	
insert into "servicos".municipio values (	334	,	'Putinga'	,	2	, true);	
insert into "servicos".municipio values (	335	,	'Quaraí'	,	6	, true);	
insert into "servicos".municipio values (	336	,	'Quatro Irmãos'	,	9	, true);	
insert into "servicos".municipio values (	337	,	'Quevedos'	,	8	, true);	
insert into "servicos".municipio values (	338	,	'Quinze de Novembro'	,	8	, true);	
insert into "servicos".municipio values (	339	,	'Redentora'	,	7	, true);	
insert into "servicos".municipio values (	340	,	'Relvado'	,	2	, true);	
insert into "servicos".municipio values (	341	,	'Restinga Seca'	,	8	, true);	
insert into "servicos".municipio values (	342	,	'Rio dos Índios'	,	9	, true);	
insert into "servicos".municipio values (	343	,	'Rio Grande'	,	5	, true);	
insert into "servicos".municipio values (	344	,	'Rio Pardo'	,	2	, true);	
insert into "servicos".municipio values (	345	,	'Riozinho'	,	1	, true);	
insert into "servicos".municipio values (	346	,	'Roca Sales'	,	2	, true);	
insert into "servicos".municipio values (	347	,	'Rodeio Bonito'	,	9	, true);	
insert into "servicos".municipio values (	348	,	'Rolador'	,	7	, true);	
insert into "servicos".municipio values (	349	,	'Rolante'	,	1	, true);	
insert into "servicos".municipio values (	350	,	'Ronda Alta'	,	9	, true);	
insert into "servicos".municipio values (	351	,	'Rondinha'	,	9	, true);	
insert into "servicos".municipio values (	352	,	'Roque Gonzales'	,	7	, true);	
insert into "servicos".municipio values (	353	,	'Rosário do Sul'	,	6	, true);	
insert into "servicos".municipio values (	354	,	'Sagrada Família'	,	9	, true);	
insert into "servicos".municipio values (	355	,	'Saldanha Marinho'	,	8	, true);	
insert into "servicos".municipio values (	356	,	'Salto do Jacuí'	,	8	, true);	
insert into "servicos".municipio values (	357	,	'Salvador das Missões'	,	7	, true);	
insert into "servicos".municipio values (	358	,	'Salvador do Sul'	,	1	, true);	
insert into "servicos".municipio values (	359	,	'Sananduva'	,	9	, true);	
insert into "servicos".municipio values (	360	,	'Santa Bárbara do Sul'	,	8	, true);	
insert into "servicos".municipio values (	361	,	'Santa Cecília do Sul'	,	9	, true);	
insert into "servicos".municipio values (	362	,	'Santa Clara do Sul'	,	2	, true);	
insert into "servicos".municipio values (	363	,	'Santa Cruz do Sul'	,	2	, true);	
insert into "servicos".municipio values (	364	,	'Santa Margarida do Sul'	,	6	, true);	
insert into "servicos".municipio values (	365	,	'Santa Maria'	,	8	, true);	
insert into "servicos".municipio values (	366	,	'Santa Maria do Herval'	,	1	, true);	
insert into "servicos".municipio values (	367	,	'Santa Rosa'	,	7	, true);	
insert into "servicos".municipio values (	368	,	'Santa Tereza'	,	3	, true);	
insert into "servicos".municipio values (	369	,	'Santa Vitória do Palmar'	,	5	, true);	
insert into "servicos".municipio values (	370	,	'Santana da Boa Vista'	,	5	, true);	
insert into "servicos".municipio values (	371	,	'Santana do Livramento'	,	6	, true);	
insert into "servicos".municipio values (	372	,	'Santiago'	,	8	, true);	
insert into "servicos".municipio values (	373	,	'Santo Ângelo'	,	7	, true);	
insert into "servicos".municipio values (	374	,	'Santo Antônio da Patrulha'	,	4	, true);	
insert into "servicos".municipio values (	375	,	'Santo Antônio das Missões'	,	7	, true);	
insert into "servicos".municipio values (	376	,	'Santo Antônio do Palma'	,	9	, true);	
insert into "servicos".municipio values (	377	,	'Santo Antônio do Planalto'	,	9	, true);	
insert into "servicos".municipio values (	378	,	'Santo Augusto'	,	7	, true);	
insert into "servicos".municipio values (	379	,	'Santo Cristo'	,	7	, true);	
insert into "servicos".municipio values (	380	,	'Santo Expedito do Sul'	,	9	, true);	
insert into "servicos".municipio values (	381	,	'São Borja'	,	6	, true);	
insert into "servicos".municipio values (	382	,	'São Domingos do Sul'	,	9	, true);	
insert into "servicos".municipio values (	383	,	'São Francisco de Assis'	,	8	, true);	
insert into "servicos".municipio values (	384	,	'São Francisco de Paula'	,	3	, true);	
insert into "servicos".municipio values (	385	,	'São Gabriel'	,	6	, true);	
insert into "servicos".municipio values (	386	,	'São Jerônimo'	,	1	, true);	
insert into "servicos".municipio values (	387	,	'São João da Urtiga'	,	9	, true);	
insert into "servicos".municipio values (	388	,	'São João do Polêsine'	,	8	, true);	
insert into "servicos".municipio values (	389	,	'São Jorge'	,	3	, true);	
insert into "servicos".municipio values (	390	,	'São José das Missões'	,	9	, true);	
insert into "servicos".municipio values (	391	,	'São José do Herval'	,	9	, true);	
insert into "servicos".municipio values (	392	,	'São José do Hortêncio'	,	1	, true);	
insert into "servicos".municipio values (	393	,	'São José do Inhacorá'	,	7	, true);	
insert into "servicos".municipio values (	394	,	'São José do Norte'	,	5	, true);	
insert into "servicos".municipio values (	395	,	'São José do Ouro'	,	9	, true);	
insert into "servicos".municipio values (	396	,	'São José do Sul'	,	1	, true);	
insert into "servicos".municipio values (	397	,	'São José dos Ausentes'	,	3	, true);	
insert into "servicos".municipio values (	398	,	'São Leopoldo'	,	1	, true);	
insert into "servicos".municipio values (	399	,	'São Lourenço do Sul'	,	5	, true);	
insert into "servicos".municipio values (	400	,	'São Luiz Gonzaga'	,	7	, true);	
insert into "servicos".municipio values (	401	,	'São Marcos'	,	3	, true);	
insert into "servicos".municipio values (	402	,	'São Martinho'	,	7	, true);	
insert into "servicos".municipio values (	403	,	'São Martinho da Serra'	,	8	, true);	
insert into "servicos".municipio values (	404	,	'São Miguel das Missões'	,	7	, true);	
insert into "servicos".municipio values (	405	,	'São Nicolau'	,	7	, true);	
insert into "servicos".municipio values (	406	,	'São Paulo das Missões'	,	7	, true);	
insert into "servicos".municipio values (	407	,	'São Pedro da Serra'	,	1	, true);	
insert into "servicos".municipio values (	408	,	'São Pedro das Missões'	,	9	, true);	
insert into "servicos".municipio values (	409	,	'São Pedro do Butiá'	,	7	, true);	
insert into "servicos".municipio values (	410	,	'São Pedro do Sul'	,	8	, true);	
insert into "servicos".municipio values (	411	,	'São Sebastião do Caí'	,	1	, true);	
insert into "servicos".municipio values (	412	,	'São Sepé'	,	8	, true);	
insert into "servicos".municipio values (	413	,	'São Valentim'	,	9	, true);	
insert into "servicos".municipio values (	414	,	'São Valentim do Sul'	,	3	, true);	
insert into "servicos".municipio values (	415	,	'São Valério do Sul'	,	7	, true);	
insert into "servicos".municipio values (	416	,	'São Vendelino'	,	1	, true);	
insert into "servicos".municipio values (	417	,	'São Vicente do Sul'	,	8	, true);	
insert into "servicos".municipio values (	418	,	'Sapiranga'	,	1	, true);	
insert into "servicos".municipio values (	419	,	'Sapucaia do Sul'	,	1	, true);	
insert into "servicos".municipio values (	420	,	'Sarandi'	,	9	, true);	
insert into "servicos".municipio values (	421	,	'Seberi'	,	9	, true);	
insert into "servicos".municipio values (	422	,	'Sede Nova'	,	7	, true);	
insert into "servicos".municipio values (	423	,	'Segredo'	,	2	, true);	
insert into "servicos".municipio values (	424	,	'Selbach'	,	8	, true);	
insert into "servicos".municipio values (	425	,	'Senador Salgado Filho'	,	7	, true);	
insert into "servicos".municipio values (	426	,	'Sentinela do Sul'	,	1	, true);	
insert into "servicos".municipio values (	427	,	'Serafina Corrêa'	,	3	, true);	
insert into "servicos".municipio values (	428	,	'Sério'	,	2	, true);	
insert into "servicos".municipio values (	429	,	'Sertão'	,	9	, true);	
insert into "servicos".municipio values (	430	,	'Sertão Santana'	,	1	, true);	
insert into "servicos".municipio values (	431	,	'Sete de Setembro'	,	7	, true);	
insert into "servicos".municipio values (	432	,	'Severiano de Almeida'	,	9	, true);	
insert into "servicos".municipio values (	433	,	'Silveira Martins'	,	8	, true);	
insert into "servicos".municipio values (	434	,	'Sinimbu'	,	2	, true);	
insert into "servicos".municipio values (	435	,	'Sobradinho'	,	2	, true);	
insert into "servicos".municipio values (	436	,	'Soledade'	,	9	, true);	
insert into "servicos".municipio values (	437	,	'Tabaí'	,	2	, true);	
insert into "servicos".municipio values (	438	,	'Tapejara'	,	9	, true);	
insert into "servicos".municipio values (	439	,	'Tapera'	,	8	, true);	
insert into "servicos".municipio values (	440	,	'Tapes'	,	1	, true);	
insert into "servicos".municipio values (	441	,	'Taquara'	,	1	, true);	
insert into "servicos".municipio values (	442	,	'Taquari'	,	2	, true);	
insert into "servicos".municipio values (	443	,	'Taquaruçu do Sul'	,	9	, true);	
insert into "servicos".municipio values (	444	,	'Tavares'	,	5	, true);	
insert into "servicos".municipio values (	445	,	'Tenente Portela'	,	7	, true);	
insert into "servicos".municipio values (	446	,	'Terra de Areia'	,	4	, true);	
insert into "servicos".municipio values (	447	,	'Teutônia'	,	2	, true);	
insert into "servicos".municipio values (	448	,	'Tio Hugo'	,	9	, true);	
insert into "servicos".municipio values (	449	,	'Tiradentes do Sul'	,	7	, true);	
insert into "servicos".municipio values (	450	,	'Toropi'	,	8	, true);	
insert into "servicos".municipio values (	451	,	'Torres'	,	4	, true);	
insert into "servicos".municipio values (	452	,	'Tramandaí'	,	4	, true);	
insert into "servicos".municipio values (	453	,	'Travesseiro'	,	2	, true);	
insert into "servicos".municipio values (	454	,	'Três Arroios'	,	9	, true);	
insert into "servicos".municipio values (	455	,	'Três Cachoeiras'	,	4	, true);	
insert into "servicos".municipio values (	456	,	'Três Coroas'	,	1	, true);	
insert into "servicos".municipio values (	457	,	'Três de Maio'	,	7	, true);	
insert into "servicos".municipio values (	458	,	'Três Forquilhas'	,	4	, true);	
insert into "servicos".municipio values (	459	,	'Três Palmeiras'	,	9	, true);	
insert into "servicos".municipio values (	460	,	'Três Passos'	,	7	, true);	
insert into "servicos".municipio values (	461	,	'Trindade do Sul'	,	9	, true);	
insert into "servicos".municipio values (	462	,	'Triunfo'	,	1	, true);	
insert into "servicos".municipio values (	463	,	'Tucunduva'	,	7	, true);	
insert into "servicos".municipio values (	464	,	'Tunas'	,	2	, true);	
insert into "servicos".municipio values (	465	,	'Tupanci do Sul'	,	9	, true);	
insert into "servicos".municipio values (	466	,	'Tupanciretã'	,	8	, true);	
insert into "servicos".municipio values (	467	,	'Tupandi'	,	1	, true);	
insert into "servicos".municipio values (	468	,	'Tuparendi'	,	7	, true);	
insert into "servicos".municipio values (	469	,	'Turuçu'	,	5	, true);	
insert into "servicos".municipio values (	470	,	'Ubiretama'	,	7	, true);	
insert into "servicos".municipio values (	471	,	'União da Serra'	,	3	, true);	
insert into "servicos".municipio values (	472	,	'Unistalda'	,	8	, true);	
insert into "servicos".municipio values (	473	,	'Uruguaiana'	,	6	, true);	
insert into "servicos".municipio values (	474	,	'Vacaria'	,	3	, true);	
insert into "servicos".municipio values (	475	,	'Vale do Sol'	,	2	, true);	
insert into "servicos".municipio values (	476	,	'Vale Real'	,	1	, true);	
insert into "servicos".municipio values (	477	,	'Vale Verde'	,	2	, true);	
insert into "servicos".municipio values (	478	,	'Vanini'	,	9	, true);	
insert into "servicos".municipio values (	479	,	'Venâncio Aires'	,	2	, true);	
insert into "servicos".municipio values (	480	,	'Vera Cruz'	,	2	, true);	
insert into "servicos".municipio values (	481	,	'Veranópolis'	,	3	, true);	
insert into "servicos".municipio values (	482	,	'Vespasiano Corrêa'	,	2	, true);	
insert into "servicos".municipio values (	483	,	'Viadutos'	,	9	, true);	
insert into "servicos".municipio values (	484	,	'Viamão'	,	1	, true);	
insert into "servicos".municipio values (	485	,	'Vicente Dutra'	,	9	, true);	
insert into "servicos".municipio values (	486	,	'Victor Graeff'	,	9	, true);	
insert into "servicos".municipio values (	487	,	'Vila Flores'	,	3	, true);	
insert into "servicos".municipio values (	488	,	'Vila Lângaro'	,	9	, true);	
insert into "servicos".municipio values (	489	,	'Vila Maria'	,	9	, true);	
insert into "servicos".municipio values (	490	,	'Vila Nova do Sul'	,	8	, true);	
insert into "servicos".municipio values (	491	,	'Vista Alegre'	,	9	, true);	
insert into "servicos".municipio values (	492	,	'Vista Alegre do Prata'	,	3	, true);	
insert into "servicos".municipio values (	493	,	'Vista Gaúcha'	,	7	, true);	
insert into "servicos".municipio values (	494	,	'Vitória das Missões'	,	7	, true);	
insert into "servicos".municipio values (	495	,	'Westfália'	,	2	, true);	
insert into "servicos".municipio values (	496	,	'Xangri-lá'	,	4	, true);	
