insert into "servicos".agencia values (   1	,	'Agência FGTAS/SINE - Alegrete'	,	'Agência'	,	6	, true);
insert into "servicos".agencia values ( 	2	,	'Agência FGTAS/SINE - Alvorada'	,	'Agência'	,	12	, true);
insert into "servicos".agencia values ( 	3	,	'Agência FGTAS/SINE - Arroio Do Meio'	,	'Agência'	,	21	, true);
insert into "servicos".agencia values ( 	4	,	'Agência FGTAS/SINE - Arroio Dos Ratos'	,	'Agência'	,	25	, true);
insert into "servicos".agencia values ( 	5	,	'Agência FGTAS/SINE - Arroio Grande'	,	'Agência'	,	26	, true);
insert into "servicos".agencia values ( 	6	,	'Agência FGTAS/SINE - Bagé'	,	'Agência'	,	30	, true);
insert into "servicos".agencia values ( 	7	,	'Agência FGTAS/SINE - Bento Gonçalves'	,	'Agência'	,	43	, true);
insert into "servicos".agencia values ( 	8	,	'Agência FGTAS/SINE - Bom Jesus'	,	'Agência'	,	49	, true);
insert into "servicos".agencia values ( 	9	,	'Agência FGTAS/SINE - Caçapava Do Sul'	,	'Agência'	,	59	, true);
insert into "servicos".agencia values ( 	10	,	'Agência FGTAS/SINE - Cacequi'	,	'Agência'	,	60	, true);
insert into "servicos".agencia values ( 	11	,	'Agência FGTAS/SINE - Cachoeira Do Sul'	,	'Agência'	,	61	, true);
insert into "servicos".agencia values ( 	12	,	'Agência FGTAS/SINE - Cachoerinha'	,	'Agência'	,	62	, true);
insert into "servicos".agencia values ( 	13	,	'Agência FGTAS/SINE - Camaquã'	,	'Agência'	,	66	, true);
insert into "servicos".agencia values ( 	14	,	'Agência FGTAS/SINE - Campinas Das Missões'	,	'Agência'	,	70	, true);
insert into "servicos".agencia values ( 	15	,	'Agência FGTAS/SINE - Campo Bom'	,	'Agência'	,	72	, true);
insert into "servicos".agencia values ( 	16	,	'Agência FGTAS/SINE - Candelária'	,	'Agência'	,	75	, true);
insert into "servicos".agencia values ( 	17	,	'Agência FGTAS/SINE - Candiota'	,	'Agência'	,	77	, true);
insert into "servicos".agencia values ( 	18	,	'Agência FGTAS/SINE - Canela'	,	'Agência'	,	78	, true);
insert into "servicos".agencia values ( 	19	,	'Agência FGTAS/SINE - Canguçú'	,	'Agência'	,	79	, true);
insert into "servicos".agencia values ( 	20	,	'Agência FGTAS/SINE - Canoas'	,	'Agência'	,	80	, true);
insert into "servicos".agencia values ( 	21	,	'Agência FGTAS/SINE - Capão Da Canoa'	,	'Agência'	,	83	, true);
insert into "servicos".agencia values ( 	22	,	'Agência FGTAS/SINE - Capão Do Leão'	,	'Agência'	,	85	, true);
insert into "servicos".agencia values ( 	23	,	'Agência FGTAS/SINE - Capela De Santana'	,	'Agência'	,	86	, true);
insert into "servicos".agencia values ( 	24	,	'Agência FGTAS/SINE - Carazinho'	,	'Agência'	,	90	, true);
insert into "servicos".agencia values ( 	25	,	'Agência FGTAS/SINE - Carlos Barbosa'	,	'Agência'	,	91	, true);
insert into "servicos".agencia values ( 	26	,	'Agência FGTAS/SINE - Caxias Do Sul'	,	'Agência'	,	96	, true);
insert into "servicos".agencia values ( 	27	,	'Agência FGTAS/SINE - Charqueadas'	,	'Agência'	,	104	, true);
insert into "servicos".agencia values ( 	28	,	'Agência FGTAS/SINE - Cidreira'	,	'Agência'	,	109	, true);
insert into "servicos".agencia values ( 	29	,	'Agência FGTAS/SINE - Constantina'	,	'Agência'	,	114	, true);
insert into "servicos".agencia values ( 	30	,	'Agência FGTAS/SINE - Crissiumal'	,	'Agência'	,	122	, true);
insert into "servicos".agencia values ( 	31	,	'Agência FGTAS/SINE - Cruz Alta'	,	'Agência'	,	125	, true);
insert into "servicos".agencia values ( 	32	,	'Agência FGTAS/SINE - Dom Pedrito'	,	'Agência'	,	136	, true);
insert into "servicos".agencia values ( 	33	,	'Agência FGTAS/SINE - Encantado'	,	'Agência'	,	142	, true);
insert into "servicos".agencia values ( 	34	,	'Agência FGTAS/SINE - Encruzilhada Do Sul'	,	'Agência'	,	143	, true);
insert into "servicos".agencia values ( 	35	,	'Agência FGTAS/SINE - Erechim'	,	'Agência'	,	148	, true);
insert into "servicos".agencia values ( 	36	,	'Agência FGTAS/SINE - Estância Velha'	,	'Agência'	,	156	, true);
insert into "servicos".agencia values ( 	37	,	'Agência FGTAS/SINE - Esteio'	,	'Agência'	,	157	, true);
insert into "servicos".agencia values ( 	38	,	'Agência FGTAS/SINE - Estrela'	,	'Agência'	,	158	, true);
insert into "servicos".agencia values ( 	39	,	'Agência FGTAS/SINE - Farroupilha'	,	'Agência'	,	162	, true);
insert into "servicos".agencia values ( 	40	,	'Agência FGTAS/SINE - Feliz'	,	'Agência'	,	166	, true);
insert into "servicos".agencia values ( 	41	,	'Agência FGTAS/SINE - Flores Da Cunha'	,	'Agência'	,	167	, true);
insert into "servicos".agencia values ( 	42	,	'Agência FGTAS/SINE - Frederico Westphalen'	,	'Agência'	,	173	, true);
insert into "servicos".agencia values ( 	43	,	'Agência FGTAS/SINE - Garibaldi'	,	'Agência'	,	174	, true);
insert into "servicos".agencia values ( 	44	,	'Agência FGTAS/SINE - Getúlio Vargas'	,	'Agência'	,	179	, true);
insert into "servicos".agencia values ( 	45	,	'Agência FGTAS/SINE - Giruá'	,	'Agência'	,	180	, true);
insert into "servicos".agencia values ( 	46	,	'Agência FGTAS/SINE - Glorinha'	,	'Agência'	,	181	, true);
insert into "servicos".agencia values ( 	47	,	'Agência FGTAS/SINE - Gramado'	,	'Agência'	,	182	, true);
insert into "servicos".agencia values ( 	48	,	'Agência FGTAS/SINE - Gravataí'	,	'Agência'	,	185	, true);
insert into "servicos".agencia values ( 	49	,	'Agência FGTAS/SINE - Guaíba'	,	'Agência'	,	187	, true);
insert into "servicos".agencia values ( 	50	,	'Agência FGTAS/SINE - Guaporé'	,	'Agência'	,	188	, true);
insert into "servicos".agencia values ( 	51	,	'Agência FGTAS/SINE - Guarani Das Missões'	,	'Agência'	,	189	, true);
insert into "servicos".agencia values ( 	52	,	'Agência FGTAS/SINE - Horizontina'	,	'Agência'	,	193	, true);
insert into "servicos".agencia values ( 	53	,	'Agência FGTAS/SINE - Ibiraiaras'	,	'Agência'	,	198	, true);
insert into "servicos".agencia values ( 	54	,	'Agência FGTAS/SINE - Ibirubá'	,	'Agência'	,	200	, true);
insert into "servicos".agencia values ( 	55	,	'Agência FGTAS/SINE - Igrejinha'	,	'Agência'	,	201	, true);
insert into "servicos".agencia values ( 	56	,	'Agência FGTAS/SINE - Ijuí'	,	'Agência'	,	202	, true);
insert into "servicos".agencia values ( 	57	,	'Agência FGTAS/SINE - Iraí'	,	'Agência'	,	210	, true);
insert into "servicos".agencia values ( 	58	,	'Agência FGTAS/SINE - Itaqui'	,	'Agência'	,	214	, true);
insert into "servicos".agencia values ( 	59	,	'Agência FGTAS/SINE - Jaguarão'	,	'Agência'	,	222	, true);
insert into "servicos".agencia values ( 	60	,	'Agência FGTAS/SINE - Lagoa Vermelha'	,	'Agência'	,	230	, true);
insert into "servicos".agencia values ( 	61	,	'Agência FGTAS/SINE - Lajeado'	,	'Agência'	,	232	, true);
insert into "servicos".agencia values ( 	62	,	'Agência FGTAS/SINE - Marau'	,	'Agência'	,	244	, true);
insert into "servicos".agencia values ( 	63	,	'Agência FGTAS/SINE - Montenegro'	,	'Agência'	,	259	, true);
insert into "servicos".agencia values ( 	64	,	'Agência FGTAS/SINE - Nonoai'	,	'Agência'	,	270	, true);
insert into "servicos".agencia values ( 	65	,	'Agência FGTAS/SINE - Nova Hartz'	,	'Agência'	,	278	, true);
insert into "servicos".agencia values ( 	66	,	'Agência FGTAS/SINE - Nova Prata'	,	'Agência'	,	282	, true);
insert into "servicos".agencia values ( 	67	,	'Agência FGTAS/SINE - Nova Santa Rita'	,	'Agência'	,	285	, true);
insert into "servicos".agencia values ( 	68	,	'Agência FGTAS/SINE - Novo Hamburgo'	,	'Agência'	,	288	, true);
insert into "servicos".agencia values ( 	69	,	'Agência FGTAS/SINE - Osório'	,	'Agência'	,	292	, true);
insert into "servicos".agencia values ( 	70	,	'Agência FGTAS/SINE - Palmares Do Sul'	,	'Agência'	,	294	, true);
insert into "servicos".agencia values ( 	71	,	'Agência FGTAS/SINE - Palmeira Das Missões'	,	'Agência'	,	295	, true);
insert into "servicos".agencia values ( 	72	,	'Agência FGTAS/SINE - Panambi'	,	'Agência'	,	297	, true);
insert into "servicos".agencia values ( 	73	,	'Agência FGTAS/SINE - Pantano Grande'	,	'Agência'	,	298	, true);
insert into "servicos".agencia values ( 	74	,	'Agência FGTAS/SINE - Parobé'	,	'Agência'	,	302	, true);
insert into "servicos".agencia values ( 	75	,	'Agência FGTAS/SINE - Passo Fundo'	,	'Agência'	,	305	, true);
insert into "servicos".agencia values ( 	76	,	'Agência FGTAS/SINE - Pelotas'	,	'Agência'	,	311	, true);
insert into "servicos".agencia values ( 	77	,	'Agência FGTAS/SINE - Pinheiro Machado'	,	'Agência'	,	317	, true);
insert into "servicos".agencia values ( 	78	,	'Agência FGTAS/SINE - Piratini'	,	'Agência'	,	319	, true);
insert into "servicos".agencia values ( 	79	,	'Agência FGTAS/SINE - Polo Petroquímico'	,	'Agência'	,	462	, true);
insert into "servicos".agencia values ( 	80	,	'Agência FGTAS/SINE - Portão'	,	'Agência'	,	324	, true);
insert into "servicos".agencia values ( 	81	,	'Porto Alegre - Azenha'	,	'Agência'	,	325	, true);
insert into "servicos".agencia values ( 	82	,	'Porto Alegre - Cristo Redentor'	,	'Agência'	,	325	, true);
insert into "servicos".agencia values ( 	83	,	'Porto Alegre - José Montaury'	,	'Agência'	,	325	, true);
insert into "servicos".agencia values ( 	84	,	'Porto Alegre - Zona Sul'	,	'Agência'	,	325	, true);
insert into "servicos".agencia values ( 	85	,	'Agência FGTAS/SINE - Quaraí'	,	'Agência'	,	335	, true);
insert into "servicos".agencia values ( 	86	,	'Agência FGTAS/SINE - Restinga Sêca'	,	'Agência'	,	341	, true);
insert into "servicos".agencia values ( 	87	,	'Agência FGTAS/SINE - Rio Grande'	,	'Agência'	,	343	, true);
insert into "servicos".agencia values ( 	88	,	'Agência FGTAS/SINE - Rio Pardo'	,	'Agência'	,	344	, true);
insert into "servicos".agencia values ( 	89	,	'Agência FGTAS/SINE - Ronda Alta'	,	'Agência'	,	350	, true);
insert into "servicos".agencia values ( 	90	,	'Agência FGTAS/SINE - Rosário Do Sul'	,	'Agência'	,	353	, true);
insert into "servicos".agencia values ( 	91	,	'Agência FGTAS/SINE - Salto Do Jacuí'	,	'Agência'	,	356	, true);
insert into "servicos".agencia values ( 	92	,	'Agência FGTAS/SINE - Salvador Do Sul'	,	'Agência'	,	358	, true);
insert into "servicos".agencia values ( 	93	,	'Agência FGTAS/SINE - Sananduva'	,	'Agência'	,	359	, true);
insert into "servicos".agencia values ( 	94	,	'Agência FGTAS/SINE - Santa Cruz Do Sul'	,	'Agência'	,	363	, true);
insert into "servicos".agencia values ( 	95	,	'Agência FGTAS/SINE - Santa Maria'	,	'Agência'	,	365	, true);
insert into "servicos".agencia values ( 	96	,	'Agência FGTAS/SINE - Santa Rosa'	,	'Agência'	,	367	, true);
insert into "servicos".agencia values ( 	97	,	'Agência FGTAS/SINE - Santa Vitória Do Palmar'	,	'Agência'	,	369	, true);
insert into "servicos".agencia values ( 	98	,	'Agência FGTAS/SINE - Santana Do Livramento'	,	'Agência'	,	371	, true);
insert into "servicos".agencia values ( 	99	,	'Agência FGTAS/SINE - Santiago'	,	'Agência'	,	372	, true);
insert into "servicos".agencia values ( 	100	,	'Agência FGTAS/SINE - Santo Ângelo'	,	'Agência'	,	373	, true);
insert into "servicos".agencia values ( 	101	,	'Agência FGTAS/SINE - Santo Antônio Da Patrulha'	,	'Agência'	,	374	, true);
insert into "servicos".agencia values ( 	102	,	'Agência FGTAS/SINE - Santo Augusto'	,	'Agência'	,	378	, true);
insert into "servicos".agencia values ( 	103	,	'Agência FGTAS/SINE - São Borja'	,	'Agência'	,	381	, true);
insert into "servicos".agencia values ( 	104	,	'Agência FGTAS/SINE - São Francisco De Assis'	,	'Agência'	,	383	, true);
insert into "servicos".agencia values ( 	105	,	'Agência FGTAS/SINE - São Francisco De Paula'	,	'Agência'	,	384	, true);
insert into "servicos".agencia values ( 	106	,	'Agência FGTAS/SINE - São Gabriel'	,	'Agência'	,	385	, true);
insert into "servicos".agencia values ( 	107	,	'Agência FGTAS/SINE - São Jerônimo'	,	'Agência'	,	386	, true);
insert into "servicos".agencia values ( 	108	,	'Agência FGTAS/SINE - São José Do Norte'	,	'Agência'	,	394	, true);
insert into "servicos".agencia values ( 	109	,	'Agência FGTAS/SINE - São Leopoldo'	,	'Agência'	,	398	, true);
insert into "servicos".agencia values ( 	110	,	'Agência FGTAS/SINE - São Lourenço Do Sul'	,	'Agência'	,	399	, true);
insert into "servicos".agencia values ( 	111	,	'Agência FGTAS/SINE - São Luiz Gonzaga'	,	'Agência'	,	400	, true);
insert into "servicos".agencia values ( 	112	,	'Agência FGTAS/SINE - São Sebastião Do Caí'	,	'Agência'	,	411	, true);
insert into "servicos".agencia values ( 	113	,	'Agência FGTAS/SINE - São Sepé'	,	'Agência'	,	412	, true);
insert into "servicos".agencia values ( 	114	,	'Agência FGTAS/SINE - Sapiranga'	,	'Agência'	,	418	, true);
insert into "servicos".agencia values ( 	115	,	'Agência FGTAS/SINE - Sapucaia Do Sul'	,	'Agência'	,	419	, true);
insert into "servicos".agencia values ( 	116	,	'Agência FGTAS/SINE - Sarandi'	,	'Agência'	,	420	, true);
insert into "servicos".agencia values ( 	117	,	'Agência FGTAS/SINE - Seberi'	,	'Agência'	,	421	, true);
insert into "servicos".agencia values ( 	118	,	'Agência FGTAS/SINE - Selbah'	,	'Agência'	,	424	, true);
insert into "servicos".agencia values ( 	119	,	'Agência FGTAS/SINE - Sobradinho'	,	'Agência'	,	435	, true);
insert into "servicos".agencia values ( 	120	,	'Agência FGTAS/SINE - Soledade'	,	'Agência'	,	436	, true);
insert into "servicos".agencia values ( 	121	,	'Agência FGTAS/SINE - Tapejara'	,	'Agência'	,	438	, true);
insert into "servicos".agencia values ( 	122	,	'Agência FGTAS/SINE - Tapes'	,	'Agência'	,	440	, true);
insert into "servicos".agencia values ( 	123	,	'Agência FGTAS/SINE - Taquara'	,	'Agência'	,	441	, true);
insert into "servicos".agencia values ( 	124	,	'Agência FGTAS/SINE - Taquari'	,	'Agência'	,	442	, true);
insert into "servicos".agencia values ( 	125	,	'Agência FGTAS/SINE - Tenente Portela'	,	'Agência'	,	445	, true);
insert into "servicos".agencia values ( 	126	,	'Agência FGTAS/SINE - Teutônia'	,	'Agência'	,	447	, true);
insert into "servicos".agencia values ( 	127	,	'Agência FGTAS/SINE - Torres'	,	'Agência'	,	451	, true);
insert into "servicos".agencia values ( 	128	,	'Agência FGTAS/SINE - Tramandaí'	,	'Agência'	,	452	, true);
insert into "servicos".agencia values ( 	129	,	'Agência FGTAS/SINE - Três Coroas'	,	'Agência'	,	456	, true);
insert into "servicos".agencia values ( 	130	,	'Agência FGTAS/SINE - Três De Maio'	,	'Agência'	,	457	, true);
insert into "servicos".agencia values ( 	131	,	'Agência FGTAS/SINE - Três Passos'	,	'Agência'	,	460	, true);
insert into "servicos".agencia values ( 	132	,	'Agência FGTAS/SINE - Tupanciretã'	,	'Agência'	,	466	, true);
insert into "servicos".agencia values ( 	133	,	'Agência FGTAS/SINE - Uruguaiana'	,	'Agência'	,	473	, true);
insert into "servicos".agencia values ( 	134	,	'Agência FGTAS/SINE - Vacaria'	,	'Agência'	,	474	, true);
insert into "servicos".agencia values ( 	135	,	'Agência FGTAS/SINE - Venâncio Aires'	,	'Agência'	,	479	, true);
insert into "servicos".agencia values ( 	136	,	'Agência FGTAS/SINE - Vera Cruz'	,	'Agência'	,	480	, true);
insert into "servicos".agencia values ( 	137	,	'Agência FGTAS/SINE - Veranópolis'	,	'Agência'	,	481	, true);
insert into "servicos".agencia values ( 	138	,	'Agência FGTAS/SINE - Viamão'	,	'Agência'	,	484	, true);

insert into "servicos".agencia values ( 	139	,	'Balcão Cidadão FGTAS/SINE - Balneário Pinhal'	,	'Balcão'	,	31	, true);
insert into "servicos".agencia values ( 	140	,	'Balcão Cidadão FGTAS/SINE - Capivari do Sul'	,	'Balcão'	,	88	, true);
insert into "servicos".agencia values ( 	141	,	'Balcão Cidadão FGTAS/SINE - Casca'	,	'Balcão'	,	93	, true);
insert into "servicos".agencia values ( 	142	,	'Balcão Cidadão FGTAS/SINE - Ernestina'	,	'Balcão'	,	149	, true);
insert into "servicos".agencia values ( 	143	,	'Balcão Cidadão FGTAS/SINE - Imbé'	,	'Balcão'	,	204	, true);
insert into "servicos".agencia values ( 	144	,	'Balcão Cidadão FGTAS/SINE - Itaara'	,	'Balcão'	,	211	, true);
insert into "servicos".agencia values ( 	145	,	'Balcão Cidadão FGTAS/SINE - Lavras do Sul'	,	'Balcão'	,	234	, true);
insert into "servicos".agencia values ( 	146	,	'Balcão Cidadão FGTAS/SINE - Lindolfo Collor'	,	'Balcão'	,	236	, true);
insert into "servicos".agencia values ( 	147	,	'Balcão Cidadão FGTAS/SINE - Mato Leitão'	,	'Balcão'	,	251	, true);
insert into "servicos".agencia values ( 	148	,	'Balcão Cidadão FGTAS/SINE - Nova Petrópolis'	,	'Balcão'	,	281	, true);
insert into "servicos".agencia values ( 	149	,	'Balcão Cidadão FGTAS/SINE - Rolante'	,	'Balcão'	,	349	, true);
insert into "servicos".agencia values ( 	150	,	'Balcão Cidadão FGTAS/SINE - São Marcos'	,	'Balcão'	,	402	, true);
insert into "servicos".agencia values ( 	151	,	'Balcão Cidadão FGTAS/SINE - São Pedro do Sul'	,	'Balcão'	,	410	, true);
insert into "servicos".agencia values ( 	152	,	'Balcão Cidadão FGTAS/SINE - Serafina Corrêa'	,	'Balcão'	,	427	, true);
insert into "servicos".agencia values ( 	153	,	'Balcão Cidadão FGTAS/SINE - Silveira Martins'	,	'Balcão'	,	433	, true);
insert into "servicos".agencia values ( 	154	,	'Balcão Cidadão FGTAS/SINE - Xangri-Lá'	,	'Balcão'	,	496	, true);
insert into "servicos".agencia values ( 	155	,	'Balcão Cidadão FGTAS/SINE - Santa Bárbara do Sul'	,	'Balcão'	,	360	, true);

insert into "servicos".agencia values ( 	156	,	'Agência FGTAS/SINE - Butiá'	,	'Agência'	,	58	, true);
insert into "servicos".agencia values ( 	157	,	'Balcão Cidadão FGTAS/SINE - Minas do Leão'	,	'Balcão'	,	254	, true);



update "servicos".agencia
set endereco = 'Praça Getúlio Vargas, 680 - Centro – CEP 97542-450' , 
   telefone = '(55)3421-1630',
   email = 'alegrete@fgtas.rs.gov.br',
   infadicionais='Telefone adicional: (55) 3421-1725
Casa do Artesão – mesmo endereço agência
Serviços: Intermediação, SD, Qualificação, PGA'
where codigo = 1;
